language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.8"
      dist: xenial
      sudo: required

install:
  - pip install -e ".[test]"
  - pip install --upgrade codecov

script:
  - pytest -vv -s --cov-report html --cov expt

after_success:
  - codecov
